---
- name: Install Ansible via Pip.
  pip:
    name: ansible
    executable: "{{ ansible_pip_executable | default(omit) }}"
    version: "{{ ansible_install_version_pip | default(omit) }}"
    extra_args: "{{ ansible_install_pip_extra_args | default(omit) }}"
