---
- name: Converge
  hosts: all
  become: true

  vars:
    ansible_install_method: pip
    ansible_install_version_pip: "2.6.2"
    ansible_install_pip_extra_args: "--user"

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.ansible
